on:
  push:
    branches:
      - master
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: '12.x'
      - name: Run npm install
        run: npm install
      - name: Run ng build
        run: npm run build -- --prod
      - uses: actions/upload-artifact@master
        with:
          name: dist
          path: dist
