on:
  pull_request:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: '12.x'
      - name: Run pnpm install
        run: |
          curl -L https://unpkg.com/@pnpm/self-installer | node
          pnpm install
      - name: Run ng test
        run: pnpm run test -- --browsers=ChromeHeadless --no-progress --no-watch
